name: Final Strike

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    # Käytetään konttia, jossa on Anchor ja Solana valmiina
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.29.0
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Program
        run: |
          echo "Starting Stealth Container Build: $(date)"
          # Kontissa on jo kaikki valmiina, ajetaan suoraan build
          anchor build
          echo "Scanning for IDL payload..."
          ls -R target/idl/

      - name: Materialize IDL to Repository
        run: |
          # Kontissa pitää asentaa git-käyttäjä uudelleen
          git config --global --add safe.directory /__w/solana-sss-engine/solana-sss-engine
          git config --global user.name "Gandalf"
          git config --global user.email "stealth@bridge.com"
          git add -f target/idl/*.json || true
          git commit -m "chore: reveal idl payload container-style" || echo "No changes"
          git push
